Feature/components
indigotech/onboard-iago-monteiro pull request #20
Opened 2020-05-15 12:30 UTC by iago-srm

2020-05-15 12:50 UTC, alanraso commented on OnboardProject/src/Pages/Users/UserDetailsPage.tsx
> +import {UserDetails} from '../../Components/UserDetails/UserDetails';
Acho que a pasta "Components" não subiu 🤔, não achei ela aqui

2020-05-15 13:43 UTC, iago-srm commented on OnboardProject/src/Pages/Users/UserDetailsPage.tsx
> +import {UserDetails} from '../../Components/UserDetails/UserDetails';
não tinha ido mesmo... Agora acho que foi

2020-05-15 17:16 UTC, alanraso requested changes
Não sei se já era pra estar nesse PR, mas faltou criar o H1 e os componentes de form, e utilizá-los na página de Login e de criação de usuário.

2020-05-15 17:16 UTC, alanraso commented on OnboardProject/src/Components/Floating Action Button/AddUserButton.tsx
> +import React from 'react';
@iago-srm 
A gente usa o padrão `kebab-case` (nem sabia que existia esse nome) nas nomenclaturas de pastas e arquivos. Ou seja, tudo minúsculo separado com tracinho `-`.

2020-05-15 17:16 UTC, alanraso commented on OnboardProject/src/Components/Floating Action Button/styledComponents.ts
> +export const StyledTouchableOpacity = styled.TouchableOpacity`
A gente tbm usa `styled` nos componentes da biblioteca, mas usamos como sufixo, não como prefixo.

2020-05-15 17:16 UTC, alanraso commented on OnboardProject/src/Components/Floating Action Button/styledComponents.ts
> +bottom: 30px;
Aqui nos valores é bom dar uma identada

2020-05-15 17:16 UTC, alanraso commented on OnboardProject/src/Components/Floating Action Button/AddUserButton.tsx
> +class AddUserButton extends React.Component<AddUserButtonProps,{}> {
Entendi a criação desse botão, porém acho que ela não foi muito efetiva nesse caso, por 2 motivos: 

1. Acho que não é um boa prática o botão ficar responsável pela navegação. Como a página tem acesso ao `componentId`, você vai precisar pasar essa info pro botão pra poder navegar, um dado que ele não precisaria saber pra cumprir o papel dele. A própria página cuidar da navegação aqui acho que seria mais conciso.

2. Esse botão não foi reutilizado. Até por conta do comprtamento 1, fica difícil reutilizar esse botão em outros lugares. E isso vai acabar fugindo a todo o propósito de consitência que essa componentização gera. Imagina, por exemplo, que você precisa mudar o seu botão primário do aplicativo, mudando a cor de fundo e a curvatura das bordas. Sabendo que o botão da página de login e o dessa página são os mesmos (e possivelmente vários outros lugares que o utilizem), você só precisaria trocar no seu código uma vez, e já seria suficiente pra trocar em todo o código. Isso seria a consistência em ação.

O intuito dessa tarefa era justamente criar os componentes que seriam reutilziados tanto na tela de login quanto na de adicionar usuário.

2020-05-15 19:10 UTC, iago-srm commented on OnboardProject/src/Components/Floating Action Button/AddUserButton.tsx
> +class AddUserButton extends React.Component<AddUserButtonProps,{}> {
Eu ia fazer o login em seguida. Resolvi começar pela lista de detalhes de usuário, pq tinha me parecido um bom lugar para aplicar componentização...

2020-05-18 12:10 UTC, alanraso commented on OnboardProject/src/Components/Floating Action Button/AddUserButton.tsx
> +class AddUserButton extends React.Component<AddUserButtonProps,{}> {
Como o tempo do onboard é limitado, achamos melhor escolher as telas de login e adição de usuário, porque elas escancaram a necessidade da componentização, dado que tem ao menos aqueles 3 componentes que o botinho citou a serem extraídos.

2020-05-18 12:11 UTC, alanraso commented on OnboardProject/src/components/floating-action-button/AddUserButton.tsx
> +
Linhas a mais aqui.

2020-05-18 12:13 UTC, alanraso approved these changes
Dada a quantidade de modificações que já foram introduzidas aqui nesse PR, acho que vale mais a pena você mergear e abrir outra branch pra fazer a track 8 do botinho.

2020-05-18 13:29 UTC, merged